### ISSUE TITLE
Cannot capture screen: System is constantly in a transition state

### ISSUE THREAD

**Issue by matis11** [smasherprog/Screen_Capture#14]
Hello!
Trying to use the example code I'm constantly receiving an expected error from `ThreadManager:67`.

```
Starting Capture Demo
Exiting Thread due to expected error 
Exiting Thread due to expected error
Exiting Thread due to expected error
...
```

I'm running the script using **CLion 2016.3** and **OS X 10.12.3**.

I would appreciate any support on this issue!

**Comment by matis11** [comment]
A small change in `CGFrameProcessor:38-47` is suppressing this issue:
```
auto Ret = DUPL_RETURN_SUCCESS;
auto imageRef = CGDisplayCreateImage(Id(_CGFrameProcessorImpl->Data->SelectedMonitor));
if(!imageRef) return DUPL_RETURN_ERROR_EXPECTED;//this happens when the monitors change.

auto width = CGImageGetWidth(imageRef);
auto height = CGImageGetHeight(imageRef);
if(width!= Width(_CGFrameProcessorImpl->Data->SelectedMonitor) || height!= Height(_CGFrameProcessorImpl->Data->SelectedMonitor)){
    CGImageRelease(imageRef);
    return DUPL_RETURN_ERROR_EXPECTED;//this happens when the monitors change.
}
```

After removing the width/height check script is capturing desktop.

**Comment by smasherprog** [comment]
Ill check this out and release a fix within a few hours.

**Comment by smasherprog** [comment]
I cannot reproduce the issue. 
Are you running mutiple monitors? Can you check what the values look like in the SelectedMonitor    data member?

**Comment by matis11** [comment]
Thanks for quick reply! For this issue I've used only one monitor (I've tested the script with commented `if` check with 2 monitors and it worked correctly).

Issue can be seen here:
![image](https://cloud.githubusercontent.com/assets/1921100/24766428/8e82dbaa-1afb-11e7-96b6-33d0bb3aa5b3.png)
Please notice incorrect height/width here.

**Comment by smasherprog** [comment]
Yeah, thats what I figured. The monitor info isnt matching the display height/width.
So, your right, it will work with the code commented out, but if you change your monitor resolution, I want the code to detect the change and reset everything for the new dimentions.

Ill take a closer look when I get home today.

**Comment by smasherprog** [comment]
Checking on this now. I suspect it is some sort or mirrored display that I am picking up

**Comment by smasherprog** [comment]
I just pushed a change to master. Please try that out. It filters out mirrored displays.

**Comment by matis11** [comment]
I've pulled master and the issue still appears. However I've noted that if I connect a second monitor script will capture only frames from the external one.
I started wondering why only retina display in my macbook is causing troubles, and after a research I think that I've found the issue:

Macbook display can be scalable (and is on by default). Hardware resolution is 2560x1600 (as `imageRef` in code), but OS X is scaling it to provide bigger fonts to a selected resolution (by default it's 1280x800 and it's not visible anywhere).

![image](https://cloud.githubusercontent.com/assets/1921100/24796390/1404acea-1b8d-11e7-9463-82721621fd97.png)

More about scaling: http://osxdaily.com/2014/04/14/change-retina-macbook-screen-resolution-more-space/

**Comment by smasherprog** [comment]
Ok great, Ill check that out. I wont be able to make any changes for another 12 hours though.

**Comment by smasherprog** [comment]
I just checked in a commit that should fix the issue. It isnt ideal because it means allocating an image, but its quickly destroyed so I guess its ok for now.

**Comment by smasherprog** [comment]
I didn't see a that there is a fun tion. Cgdisplaypixelswidth. And height.  So ill try that out when I am home later today. In the mean time.   Is the current fix working?

**Comment by smasherprog** [comment]
Just commited to master the CGDisplayPixelsHigh and CGDisplayPixelsWide    functions for the GetMonitors. All of the bugs should be fixed. 

Let me know if they are not.

**Comment by smasherprog** [comment]
Closing issue.
If the problem still isnt fixed, please comment

**Comment by rcmalli** [comment]
Mac OS 10.2.2. The error still happens when trying the demo code. I only using one monitor which is laptop's default. I also tried with both scaled and not scaled resolutions. Demo code still prints out "Exiting Thread due to expected error "

**Comment by smasherprog** [comment]
I just double checked my mac os version and I was running 10.11.6   so I am updating it now to the latests and I hope it will allow me to reproduce the error you guys are getting

**Comment by smasherprog** [comment]
I am now able to recreate this error so ill get it fixed asap

**Comment by smasherprog** [comment]
Just Committed to master a change that fixes the bug.. For sure this time.

**Comment by smasherprog** [comment]
Im going to close this. Please post a comment if this didnt fix the issue
